[build]
  publish = "public"
  command = "echo 'Static site - no build needed'"

# Serve JSON files with correct content type
[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

# Serve video files with correct content type
[[headers]]
  for = "/videos/*"
  [headers.values]
    Content-Type = "video/mp4"

# SPA fallback - only for non-existent routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
