[build]
  publish = "public"
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/videos/*"
  to = "/videos/:splat"
  status = 200

[[headers]]
  for = "/videos/*"
  [headers.values]
    Content-Type = "video/mp4"
